import { wireTheme } from './theme';
import { wireTabs } from './tabs';
import { wireFilters, applyFilters } from './filters';
import { wireAllCards } from './cards';
import { wireSearch } from './search';
import { wireRoute } from './route';
import { wireShopping } from './shopping';
import { wireShare } from './share';
import { wireExport } from './export';
import { wirePWA } from './pwa';
import { wireTagClicks } from './tags';
import { wireFilterTray } from './filter-tray';
import { wireHeaderMenu } from './header-menu';
import { wireFiltersPanel } from './filters-panel';

wireTheme();
wireAllCards();
wireTagClicks();
wireTabs();
wireFilters();
wireRoute();
wireShopping();
wireSearch();
wireFilterTray();
wireHeaderMenu();
wireFiltersPanel();
wireShare();
wireExport();
wirePWA();
applyFilters();
